
export const TemplateConfigS1=
[
    {
        Name:'ProjectName',
        DisplayName:'שם הפרויקט',
        fieldType:'text',
        isMandatory:true,
        minimum:5,
        maximum:Infinity,
        alertText:'שם הפרויקט חסר'
    },
    {
        Name:'CStackholders',
        DisplayName:'בעלי עניין',
        fieldType:'text',
        isMandatory:true,
        minimum:-Infinity,
        maximum:Infinity,
        alertText:'חסר שדה בעלי עניין'
    },
    {
        Name:'CustCustomers',
        DisplayName:'משתמשי מערכת',
        fieldType:'text',
        isMandatory:true,
        minimum:-Infinity,
        maximum:Infinity,
        alertText:'חסר שדה משתמשי מערכת'
    },
    {
        Name:'CDescription',
        DisplayName:'תיאור קצר',
        alertText:'תיאור קצר צריך להיות בין 50 ל-150 תווים',
        minimum:50,
        maximum:150,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'PDescription',
        DisplayName:'תיאור הפרויקט',
        alertText:'תיאור הפרויקט צריך להיות בין 200 ל-500 תווים',
        minimum:200,
        maximum:500,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'Challenges',
        DisplayName:'אתגרי הפרויקט',
        alertText:'שדה אתגרי הפרויקט צריך להיות בין 50 ל-200 תווים',
        minimum:50,
        maximum:200,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'Comments',
        DisplayName:'הערות',
        alertText:'שדה הערות אינו חובה אך במידה ומילאתם אותו דרושים מינימום 5 תווים',
        minimum:5,
        maximum:Infinity,
        isMandatory:false,
        fieldType:'text',
    },
    {
        Name:'ProjectTopic',
        DisplayName:'נושא הפרויקט',
        alertText:'חסר נושא הפרויקט',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Year',
        DisplayName:'שנת הפרויקט',
        alertText:'חסרה שנת הפרויקט',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Semester',
        DisplayName:'סמסטר',
        alertText:'חסר סמסטר',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[0]',
        DisplayName:'מנחה חלק א',
        alertText:'חסר מנחה חלק א',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[1]',
        DisplayName:'מנחה חלק ב',
        alertText:'חסר מנחה חלק ב',
        isMandatory:true,
        fieldType:'select',
    },
    
    {
        Name:'Goals',
        DisplayName:'מטרות הפרויקט',
        alertText:'מספר מטרות הפרויקט צריך להיות לפחות 2',
        isMandatory:true,
        fieldType:'array',
        minimum:2,
        maximum:Infinity,
    },
    {
        Name:'GoalDescription',
        DisplayName:'תיאור מטרה',
        alertText:'תיאור המטרה צריך להיות בין 2 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:2,
        maximum:100,
        LinkedArray:'Goals'
    },
    {
        Name:'GoalStatus',
        DisplayName:'סטטוס מטרה',
        alertText:'סטטוס המטרה צריך להיות בין 2 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:2,
        maximum:100,
        LinkedArray:'Goals'
    },
    {
        Name:'Module',
        DisplayName:'מודולי הפרויקט',
        alertText:'מספר מודולי הפרויקט צריך להיות לפחות 2',
        isMandatory:true,
        fieldType:'array',
        minimum:2,
        maximum:Infinity,
    },
    {
        Name:'ModuleName',
        DisplayName:'שם המודול',
        alertText:'שם המודול צריך להיות בין 3 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:3,
        maximum:100,
        LinkedArray:'Module'
    },
    {
        Name:'ModuleDescription',
        DisplayName:'תיאור מודול',
        alertText:'תיאור המודול צריך להיות בין 20 תווים ל-400',
        isMandatory:true,
        fieldType:'text',
        minimum:20,
        maximum:400,
        LinkedArray:'Module'
    },
    {
        Name:'Technologies',
        DisplayName:'טכנולוגיות',
        alertText:'מספר הטכנולוגיות צריך להיות לפחות 5',
        isMandatory:true,
        fieldType:'array',
        minimum:5,
        maximum:Infinity,
    },
    {
        Name:'ScreenShots',
        DisplayName:'תמונות מסך',
        alertText:'מספר תמונות מסך צריך להיות לפחות 5',
        isMandatory:true,
        fieldType:'array',
        minimum:5,
        maximum:Infinity,
    },
    {
        Name:'ProjectLogo',
        DisplayName:'לוגו הפרויקט',
        alertText:'חסר לוגו פרויקט',
        isMandatory:true,
        fieldType:'array',
        minimum:1,
        maximum:1,
    },
    {
        Name:'Github',
        DisplayName:'קישור לגיטהאב',
        alertText:'חסר קישור לגיטהאב',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
    },
    {
        Name:'Students',
        DisplayName:'מספר הסטודנטים',
        alertText:'מספר הסטודנטים צריך להיות לפחות 1',
        isMandatory:true,
        fieldType:'array',
        minimum:1,
        maximum:Infinity,
    },
    {
        Name:'Name',
        DisplayName:'שם הסטודנט',
        alertText:'שם הסטודנט חסר',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
        LinkedArray:'Students'
    },
    {
        Name:'Picture',
        DisplayName:'תמונת הסטודנט',
        alertText:'תמונת הסטודנט חסרה',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
        LinkedArray:'Students'
    },
]
export const TemplateConfigS2=
[
    {
        Name:'ProjectName',
        DisplayName:'שם הפרויקט',
        fieldType:'text',
        isMandatory:true,
        minimum:5,
        maximum:Infinity,
        alertText:'שם הפרויקט חסר'
    },
    {
        Name:'CStackholders',
        DisplayName:'בעלי עניין',
        fieldType:'text',
        isMandatory:true,
        minimum:-Infinity,
        maximum:Infinity,
        alertText:'חסר שדה בעלי עניין'
    },
    {
        Name:'CDescription',
        DisplayName:'תיאור קצר',
        alertText:'תיאור קצר צריך להיות בין 50 ל-150 תווים',
        minimum:50,
        maximum:150,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'PDescription',
        DisplayName:'תיאור הפרויקט',
        alertText:'תיאור הפרויקט צריך להיות בין 200 ל-500 תווים',
        minimum:200,
        maximum:500,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'Challenges',
        DisplayName:'אתגרי הפרויקט',
        alertText:'שדה אתגרי הפרויקט צריך להיות בין 50 ל-200 תווים',
        minimum:50,
        maximum:200,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'Comments',
        DisplayName:'הערות',
        alertText:'שדה הערות אינו חובה אך במידה ומילאתם אותו דרושים מינימום 5 תווים',
        minimum:5,
        maximum:Infinity,
        isMandatory:false,
        fieldType:'text',
    },
    {
        Name:'ProjectTopic',
        DisplayName:'נושא הפרויקט',
        alertText:'חסר נושא הפרויקט',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Year',
        DisplayName:'שנת הפרויקט',
        alertText:'חסרה שנת הפרויקט',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Semester',
        DisplayName:'סמסטר',
        alertText:'חסר סמסטר',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[0]',
        DisplayName:'מנחה חלק א',
        alertText:'חסר מנחה חלק א',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[1]',
        DisplayName:'מנחה חלק ב',
        alertText:'חסר מנחה חלק ב',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[1]',
        DisplayName:'מנחה חלק ב',
        alertText:'חסר מנחה חלק ב',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Goals',
        DisplayName:'מטרות הפרויקט',
        alertText:'מספר מטרות הפרויקט צריך להיות לפחות 2',
        isMandatory:true,
        fieldType:'array',
        minimum:2,
        maximum:Infinity,
    },
    {
        Name:'GoalDescription',
        DisplayName:'תיאור מטרה',
        alertText:'תיאור המטרה צריך להיות בין 2 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:2,
        maximum:100,
        LinkedArray:'Goals'
    },
    {
        Name:'GoalStatus',
        DisplayName:'סטטוס מטרה',
        alertText:'סטטוס המטרה צריך להיות בין 2 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:2,
        maximum:100,
        LinkedArray:'Goals'
    },
    {
        Name:'Module',
        DisplayName:'מודולי הפרויקט',
        alertText:'מספר מודולי הפרויקט צריך להיות לפחות 2',
        isMandatory:true,
        fieldType:'array',
        minimum:2,
        maximum:Infinity,
    },
    {
        Name:'ModuleName',
        DisplayName:'שם המודול',
        alertText:'שם המודול צריך להיות בין 3 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:3,
        maximum:100,
        LinkedArray:'Module'
    },
    {
        Name:'ModuleDescription',
        DisplayName:'תיאור מודול',
        alertText:'תיאור המודול צריך להיות בין 20 תווים ל-400',
        isMandatory:true,
        fieldType:'text',
        minimum:20,
        maximum:400,
        LinkedArray:'Module'
    },
    {
        Name:'Technologies',
        DisplayName:'טכנולוגיות',
        alertText:'מספר הטכנולוגיות צריך להיות לפחות 5',
        isMandatory:true,
        fieldType:'array',
        minimum:5,
        maximum:Infinity,
    },
    {
        Name:'ScreenShots',
        DisplayName:'תמונות מסך',
        alertText:'מספר תמונות מסך צריך להיות לפחות 5',
        isMandatory:true,
        fieldType:'array',
        minimum:5,
        maximum:Infinity,
    },
    {
        Name:'ProjectLogo',
        DisplayName:'לוגו הפרויקט',
        alertText:'חסר לוגו פרויקט',
        isMandatory:true,
        fieldType:'array',
        minimum:1,
        maximum:1,
    },
    {
        Name:'Github',
        DisplayName:'קישור לגיטהאב',
        alertText:'חסר קישור לגיטהאב',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
    },
    {
        Name:'Students',
        DisplayName:'מספר הסטודנטים',
        alertText:'מספר הסטודנטים צריך להיות לפחות 1',
        isMandatory:true,
        fieldType:'array',
        minimum:1,
        maximum:Infinity,
    },
    {
        Name:'Name',
        DisplayName:'שם הסטודנט',
        alertText:'שם הסטודנט חסר',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
        LinkedArray:'Students'
    },
    {
        Name:'Picture',
        DisplayName:'תמונת הסטודנט',
        alertText:'תמונת הסטודנט חסרה',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
        LinkedArray:'Students'
    },
]
export const TemplateConfigS3=
[
    {
        Name:'ProjectName',
        DisplayName:'שם הפרויקט',
        fieldType:'text',
        isMandatory:true,
        minimum:5,
        maximum:Infinity,
        alertText:'שם הפרויקט חסר'
    },
    {
        Name:'CStackholders',
        DisplayName:'בעלי עניין',
        fieldType:'text',
        isMandatory:true,
        minimum:-Infinity,
        maximum:Infinity,
        alertText:'חסר שדה בעלי עניין'
    },
    {
        Name:'CDescription',
        DisplayName:'תיאור קצר',
        alertText:'תיאור קצר צריך להיות בין 50 ל-150 תווים',
        minimum:50,
        maximum:150,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'PDescription',
        DisplayName:'תיאור הפרויקט',
        alertText:'תיאור הפרויקט צריך להיות בין 200 ל-500 תווים',
        minimum:200,
        maximum:500,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'Challenges',
        DisplayName:'אתגרי הפרויקט',
        alertText:'שדה אתגרי הפרויקט צריך להיות בין 50 ל-200 תווים',
        minimum:50,
        maximum:200,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'Comments',
        DisplayName:'הערות',
        alertText:'שדה הערות אינו חובה אך במידה ומילאתם אותו דרושים מינימום 5 תווים',
        minimum:5,
        maximum:Infinity,
        isMandatory:false,
        fieldType:'text',
    },
    {
        Name:'ProjectTopic',
        DisplayName:'נושא הפרויקט',
        alertText:'חסר נושא הפרויקט',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Year',
        DisplayName:'שנת הפרויקט',
        alertText:'חסרה שנת הפרויקט',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Semester',
        DisplayName:'סמסטר',
        alertText:'חסר סמסטר',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[0]',
        DisplayName:'מנחה חלק א',
        alertText:'חסר מנחה חלק א',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[1]',
        DisplayName:'מנחה חלק ב',
        alertText:'חסר מנחה חלק ב',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[1]',
        DisplayName:'מנחה חלק ב',
        alertText:'חסר מנחה חלק ב',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Goals',
        DisplayName:'מטרות הפרויקט',
        alertText:'מספר מטרות הפרויקט צריך להיות לפחות 2',
        isMandatory:true,
        fieldType:'array',
        minimum:2,
        maximum:Infinity,
    },
    {
        Name:'GoalDescription',
        DisplayName:'תיאור מטרה',
        alertText:'תיאור המטרה צריך להיות בין 2 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:2,
        maximum:100,
        LinkedArray:'Goals'
    },
    {
        Name:'GoalStatus',
        DisplayName:'סטטוס מטרה',
        alertText:'סטטוס המטרה צריך להיות בין 2 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:2,
        maximum:100,
        LinkedArray:'Goals'
    },
    {
        Name:'Module',
        DisplayName:'מודולי הפרויקט',
        alertText:'מספר מודולי הפרויקט צריך להיות לפחות 2',
        isMandatory:true,
        fieldType:'array',
        minimum:2,
        maximum:Infinity,
    },
    {
        Name:'ModuleName',
        DisplayName:'שם המודול',
        alertText:'שם המודול צריך להיות בין 3 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:3,
        maximum:100,
        LinkedArray:'Module'
    },
    {
        Name:'ModuleDescription',
        DisplayName:'תיאור מודול',
        alertText:'תיאור המודול צריך להיות בין 20 תווים ל-400',
        isMandatory:true,
        fieldType:'text',
        minimum:20,
        maximum:400,
        LinkedArray:'Module'
    },
    {
        Name:'Technologies',
        DisplayName:'טכנולוגיות',
        alertText:'מספר הטכנולוגיות צריך להיות לפחות 5',
        isMandatory:true,
        fieldType:'array',
        minimum:5,
        maximum:Infinity,
    },
    {
        Name:'ScreenShots',
        DisplayName:'תמונות מסך',
        alertText:'מספר תמונות מסך צריך להיות לפחות 5',
        isMandatory:true,
        fieldType:'array',
        minimum:5,
        maximum:Infinity,
    },
    {
        Name:'ProjectLogo',
        DisplayName:'לוגו הפרויקט',
        alertText:'חסר לוגו פרויקט',
        isMandatory:true,
        fieldType:'array',
        minimum:1,
        maximum:1,
    },
    {
        Name:'Github',
        DisplayName:'קישור לגיטהאב',
        alertText:'חסר קישור לגיטהאב',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
    },
    {
        Name:'Students',
        DisplayName:'מספר הסטודנטים',
        alertText:'מספר הסטודנטים צריך להיות לפחות 1',
        isMandatory:true,
        fieldType:'array',
        minimum:1,
        maximum:Infinity,
    },
    {
        Name:'Name',
        DisplayName:'שם הסטודנט',
        alertText:'שם הסטודנט חסר',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
        LinkedArray:'Students'
    },
    {
        Name:'Picture',
        DisplayName:'תמונת הסטודנט',
        alertText:'תמונת הסטודנט חסרה',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
        LinkedArray:'Students'
    },
]
export const TemplateConfigS4=
[
    {
        Name:'ProjectName',
        DisplayName:'שם הפרויקט',
        fieldType:'text',
        isMandatory:true,
        minimum:5,
        maximum:Infinity,
        alertText:'שם הפרויקט חסר'
    },
    {
        Name:'CStackholders',
        DisplayName:'בעלי עניין',
        fieldType:'text',
        isMandatory:true,
        minimum:-Infinity,
        maximum:Infinity,
        alertText:'חסר שדה בעלי עניין'
    },
    {
        Name:'CDescription',
        DisplayName:'תיאור קצר',
        alertText:'תיאור קצר צריך להיות בין 50 ל-150 תווים',
        minimum:50,
        maximum:150,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'PDescription',
        DisplayName:'תיאור הפרויקט',
        alertText:'תיאור הפרויקט צריך להיות בין 200 ל-500 תווים',
        minimum:200,
        maximum:500,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'Challenges',
        DisplayName:'אתגרי הפרויקט',
        alertText:'שדה אתגרי הפרויקט צריך להיות בין 50 ל-200 תווים',
        minimum:50,
        maximum:200,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'Comments',
        DisplayName:'הערות',
        alertText:'שדה הערות אינו חובה אך במידה ומילאתם אותו דרושים מינימום 5 תווים',
        minimum:5,
        maximum:Infinity,
        isMandatory:false,
        fieldType:'text',
    },
    {
        Name:'ProjectTopic',
        DisplayName:'נושא הפרויקט',
        alertText:'חסר נושא הפרויקט',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Year',
        DisplayName:'שנת הפרויקט',
        alertText:'חסרה שנת הפרויקט',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Semester',
        DisplayName:'סמסטר',
        alertText:'חסר סמסטר',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[0]',
        DisplayName:'מנחה חלק א',
        alertText:'חסר מנחה חלק א',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[1]',
        DisplayName:'מנחה חלק ב',
        alertText:'חסר מנחה חלק ב',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[1]',
        DisplayName:'מנחה חלק ב',
        alertText:'חסר מנחה חלק ב',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Goals',
        DisplayName:'מטרות הפרויקט',
        alertText:'מספר מטרות הפרויקט צריך להיות לפחות 2',
        isMandatory:true,
        fieldType:'array',
        minimum:2,
        maximum:Infinity,
    },
    {
        Name:'GoalDescription',
        DisplayName:'תיאור מטרה',
        alertText:'תיאור המטרה צריך להיות בין 2 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:2,
        maximum:100,
        LinkedArray:'Goals'
    },
    {
        Name:'GoalStatus',
        DisplayName:'סטטוס מטרה',
        alertText:'סטטוס המטרה צריך להיות בין 2 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:2,
        maximum:100,
        LinkedArray:'Goals'
    },
    {
        Name:'Module',
        DisplayName:'מודולי הפרויקט',
        alertText:'מספר מודולי הפרויקט צריך להיות לפחות 2',
        isMandatory:true,
        fieldType:'array',
        minimum:2,
        maximum:Infinity,
    },
    {
        Name:'ModuleName',
        DisplayName:'שם המודול',
        alertText:'שם המודול צריך להיות בין 3 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:3,
        maximum:100,
        LinkedArray:'Module'
    },
    {
        Name:'ModuleDescription',
        DisplayName:'תיאור מודול',
        alertText:'תיאור המודול צריך להיות בין 20 תווים ל-400',
        isMandatory:true,
        fieldType:'text',
        minimum:20,
        maximum:400,
        LinkedArray:'Module'
    },
    {
        Name:'Technologies',
        DisplayName:'טכנולוגיות',
        alertText:'מספר הטכנולוגיות צריך להיות לפחות 5',
        isMandatory:true,
        fieldType:'array',
        minimum:5,
        maximum:Infinity,
    },
    {
        Name:'ScreenShots',
        DisplayName:'תמונות מסך',
        alertText:'מספר תמונות מסך צריך להיות לפחות 5',
        isMandatory:true,
        fieldType:'array',
        minimum:5,
        maximum:Infinity,
    },
    {
        Name:'ProjectLogo',
        DisplayName:'לוגו הפרויקט',
        alertText:'חסר לוגו פרויקט',
        isMandatory:true,
        fieldType:'array',
        minimum:1,
        maximum:1,
    },
    {
        Name:'Github',
        DisplayName:'קישור לגיטהאב',
        alertText:'חסר קישור לגיטהאב',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
    },
    {
        Name:'Students',
        DisplayName:'מספר הסטודנטים',
        alertText:'מספר הסטודנטים צריך להיות לפחות 1',
        isMandatory:true,
        fieldType:'array',
        minimum:1,
        maximum:Infinity,
    },
    {
        Name:'Name',
        DisplayName:'שם הסטודנט',
        alertText:'שם הסטודנט חסר',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
        LinkedArray:'Students'
    },
    {
        Name:'Picture',
        DisplayName:'תמונת הסטודנט',
        alertText:'תמונת הסטודנט חסרה',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
        LinkedArray:'Students'
    },
]
export const TemplateConfigS5=
[
    {
        Name:'ProjectName',
        DisplayName:'שם הפרויקט',
        fieldType:'text',
        isMandatory:true,
        minimum:5,
        maximum:Infinity,
        alertText:'שם הפרויקט חסר'
    },
    {
        Name:'CStackholders',
        DisplayName:'בעלי עניין',
        fieldType:'text',
        isMandatory:true,
        minimum:-Infinity,
        maximum:Infinity,
        alertText:'חסר שדה בעלי עניין'
    },
    {
        Name:'CDescription',
        DisplayName:'תיאור קצר',
        alertText:'תיאור קצר צריך להיות בין 50 ל-150 תווים',
        minimum:50,
        maximum:150,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'PDescription',
        DisplayName:'תיאור הפרויקט',
        alertText:'תיאור הפרויקט צריך להיות בין 200 ל-500 תווים',
        minimum:200,
        maximum:500,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'Challenges',
        DisplayName:'אתגרי הפרויקט',
        alertText:'שדה אתגרי הפרויקט צריך להיות בין 50 ל-200 תווים',
        minimum:50,
        maximum:200,
        isMandatory:true,
        fieldType:'text',
    },
    {
        Name:'Comments',
        DisplayName:'הערות',
        alertText:'שדה הערות אינו חובה אך במידה ומילאתם אותו דרושים מינימום 5 תווים',
        minimum:5,
        maximum:Infinity,
        isMandatory:false,
        fieldType:'text',
    },
    {
        Name:'ProjectTopic',
        DisplayName:'נושא הפרויקט',
        alertText:'חסר נושא הפרויקט',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Year',
        DisplayName:'שנת הפרויקט',
        alertText:'חסרה שנת הפרויקט',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Semester',
        DisplayName:'סמסטר',
        alertText:'חסר סמסטר',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[0]',
        DisplayName:'מנחה חלק א',
        alertText:'חסר מנחה חלק א',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[1]',
        DisplayName:'מנחה חלק ב',
        alertText:'חסר מנחה חלק ב',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'advisor[1]',
        DisplayName:'מנחה חלק ב',
        alertText:'חסר מנחה חלק ב',
        isMandatory:true,
        fieldType:'select',
    },
    {
        Name:'Goals',
        DisplayName:'מטרות הפרויקט',
        alertText:'מספר מטרות הפרויקט צריך להיות לפחות 2',
        isMandatory:true,
        fieldType:'array',
        minimum:2,
        maximum:Infinity,
    },
    {
        Name:'GoalDescription',
        DisplayName:'תיאור מטרה',
        alertText:'תיאור המטרה צריך להיות בין 2 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:2,
        maximum:100,
        LinkedArray:'Goals'
    },
    {
        Name:'GoalStatus',
        DisplayName:'סטטוס מטרה',
        alertText:'סטטוס המטרה צריך להיות בין 2 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:2,
        maximum:100,
        LinkedArray:'Goals'
    },
    {
        Name:'Module',
        DisplayName:'מודולי הפרויקט',
        alertText:'מספר מודולי הפרויקט צריך להיות לפחות 2',
        isMandatory:true,
        fieldType:'array',
        minimum:2,
        maximum:Infinity,
    },
    {
        Name:'ModuleName',
        DisplayName:'שם המודול',
        alertText:'שם המודול צריך להיות בין 3 תווים ל-100',
        isMandatory:true,
        fieldType:'text',
        minimum:3,
        maximum:100,
        LinkedArray:'Module'
    },
    {
        Name:'ModuleDescription',
        DisplayName:'תיאור מודול',
        alertText:'תיאור המודול צריך להיות בין 20 תווים ל-400',
        isMandatory:true,
        fieldType:'text',
        minimum:20,
        maximum:400,
        LinkedArray:'Module'
    },
    {
        Name:'Technologies',
        DisplayName:'טכנולוגיות',
        alertText:'מספר הטכנולוגיות צריך להיות לפחות 5',
        isMandatory:true,
        fieldType:'array',
        minimum:5,
        maximum:Infinity,
    },
    {
        Name:'ScreenShots',
        DisplayName:'תמונות מסך',
        alertText:'מספר תמונות מסך צריך להיות לפחות 5',
        isMandatory:true,
        fieldType:'array',
        minimum:5,
        maximum:Infinity,
    },
    {
        Name:'ProjectLogo',
        DisplayName:'לוגו הפרויקט',
        alertText:'חסר לוגו פרויקט',
        isMandatory:true,
        fieldType:'array',
        minimum:1,
        maximum:1,
    },
    {
        Name:'Github',
        DisplayName:'קישור לגיטהאב',
        alertText:'חסר קישור לגיטהאב',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
    },
    {
        Name:'Students',
        DisplayName:'מספר הסטודנטים',
        alertText:'מספר הסטודנטים צריך להיות לפחות 1',
        isMandatory:true,
        fieldType:'array',
        minimum:1,
        maximum:Infinity,
    },
    {
        Name:'Name',
        DisplayName:'שם הסטודנט',
        alertText:'שם הסטודנט חסר',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
        LinkedArray:'Students'
    },
    {
        Name:'Picture',
        DisplayName:'תמונת הסטודנט',
        alertText:'תמונת הסטודנט חסרה',
        isMandatory:true,
        fieldType:'text',
        minimum:-Infinity,
        maximum:Infinity,
        LinkedArray:'Students'
    },
]

